### ISSUE TITLE
send message according status configured on drone file.

### ISSUE THREAD

**Issue by lunny** [lddsb/drone-dingtalk-message#16]

**Comment by lddsb** [comment]
do you mean different status send different message?

**Comment by lunny** [comment]
I just want to receive the message when ci failed.

**Comment by lddsb** [comment]
maybe you can try the  [steps condition](https://docs.drone.io/pipeline/exec/syntax/steps/), example 
```yaml
---
steps:
- name: notification
  image: lddsb/drone-dingtalk-message
  when:
    status:
    - failure
```
