### ISSUE TITLE
Always send success messages

### ISSUE THREAD

**Issue by Ethan-Liuu** [lddsb/drone-dingtalk-message#24]
您好，我用的自定义模板，但是甭管构建失败还是成功发送的都是成功的消息。
![image](https://user-images.githubusercontent.com/62549795/80452483-f643fe80-8958-11ea-849f-af43a22901a4.png)

![image](https://user-images.githubusercontent.com/62549795/80452769-86824380-8959-11ea-8fab-0b761a1543a2.png)

![image](https://user-images.githubusercontent.com/62549795/80452800-9732b980-8959-11ea-8301-262ffad564f4.png)

```yaml
- name: dingtalk-failure
  image: registry.cn-beijing.aliyuncs.com/zx-common/drone-dingtalk:1.1
  settings:
    token:
      from_secret: dingtalk_token
    type: markdown
    success_color: "008000"
    failure_color: "FF0000"
    success_pic: "https://raw.githubusercontent.com/Ethan-Liuu/picture/master/success.png"
    failure_pic: "https://raw.githubusercontent.com/Ethan-Liuu/picture/master/failed.png"
  when:
    status:
    - failure
    - success
```

**Comment by lddsb** [comment]
麻烦提供一下 drone 的版本

**Comment by Ethan-Liuu** [comment]
drone 版本是 1.6.5用的helm安装

**Comment by Ethan-Liuu** [comment]
> 麻烦提供一下drone的版本

drone 版本是 1.6.5用的helm安装

**Comment by Ethan-Liuu** [comment]
您 README 这里有一个笔误
![image](https://user-images.githubusercontent.com/62549795/80454610-e9290e80-895c-11ea-8b7f-2cc11892bd6c.png)

**Comment by lddsb** [comment]
> 您 README 这里有一个笔误
> ![image](https://user-images.githubusercontent.com/62549795/80454610-e9290e80-895c-11ea-8b7f-2cc11892bd6c.png)

暴露学渣本质了。。

这个问题有可能是新版本的 drone里面的环境变量含义更改了，要等我有空试一下新版本才好做出判断。

**Comment by Ethan-Liuu** [comment]
那我就先这么用的。谢谢您了
```yaml
- name: dingtalk-success
  image: registry.cn-beijing.aliyuncs.com/zx-common/drone-dingtalk:1.1
  settings:
    token:
      from_secret: dingtalk_token
    type: markdown
    success_color: "008000"
    success_pic: "https://raw.githubusercontent.com/Ethan-Liuu/picture/master/success.png"
  when:
    status:
    - success

- name: dingtalk-failure
  image: registry.cn-beijing.aliyuncs.com/zx-common/drone-dingtalk:1.2
  settings:
    token:
      from_secret: dingtalk_token
    type: markdown
    success_color: "FF0000"
    success_pic: "https://raw.githubusercontent.com/Ethan-Liuu/picture/master/failed.png"
  when:
    status:
    - failure
```
