### ISSUE TITLE
为什么一直是  takes 0s ，我需要设置哪里？

### ISSUE THREAD

**Issue by YahuiWong** [lddsb/drone-dingtalk-message#25]
钉钉消息上面显示是 build success (takes 0s)
但是我看到 drone里面总共用时 是 01:59
我需要设置哪里？

**Comment by YahuiWong** [comment]
@lddsb 是否可以帮助解答一下这个疑惑，谢谢

**Comment by lddsb** [comment]
麻烦提供下drone版本和插件版本

**Comment by YahuiWong** [comment]
我的`.drone.yml`如下
```YAML
kind: pipeline
type: docker
name: default

steps:
……
-   name: DingTalk
    image: lddsb/drone-dingtalk-message
    settings:
        token: ……
        type: markdown
    when:
        status: [ success, failure ]
```

drone版本是 drone/drone-runner-docker 和drone/drone的latest版本
