### ISSUE TITLE
title want to include repo name

### ISSUE THREAD

**Issue by ywyt738** [lddsb/drone-dingtalk-message#3]

**Comment by lddsb** [comment]
#4 maybe this pr can solve your problem

**Comment by lddsb** [comment]
maybe we can close this issue

**Comment by ywyt738** [comment]
i use the new version 1.2.0
config:

```
- name: dingtalk
  image: lddsb/drone-dingtalk-message:v1.2.0
  settings:
    token:
      from_secret: dingtalk_token
    tpl: http://xxx.com/dingtalk_tpl_for_for_drone.tpl
    type: markdown
  when:
    status:
    - success
    - failure
```
it report ``api custom error: {code: 101002, msg: markdown is too long}``
