### ISSUE TITLE
gitlab ci状态判断不正确

### ISSUE THREAD

**Issue by pc10201** [lddsb/drone-dingtalk-message#36]
使用的是默认模板
https://raw.fastgit.org/lddsb/drone-dingtalk-message/master/tpls/gitlab-ci.tpl

当gitlab ci上一个任务执行失败时，仍然返回的是sucess

TPL_BUILD_STATUS的值获取不正确

关键代码 

stage: notify
  image: lddsb/drone-dingtalk-message:1.2.7
  script:
    - drone-dingtalk
  when: always

**Comment by lddsb** [comment]
这个目前确实是有问题。
然后我去看了一下GitLab的官方文档，似乎是 `>=13.5` 才有 `CI_JOB_STATUS` 这个环境变量，以前的版本都不具备判断job状态的能力，实在抱歉没有做足够的测试，导致了你有不好的使用体验。
我会继续想办法看怎么优雅地解决这个问题。

**Comment by pc10201** [comment]
也不能怪你，我现在用的是gitlab 14的版本，CI_JOB_STATUS这个变量的值不符合预期
我现在是分成两段来写的

> 
```yaml
notify_on_failure:
  stage: notify
  image: lddsb/drone-dingtalk-message:1.2.7
  script:
    - drone-dingtalk --build.status failure
  when: on_failure

notify_on_success:
  stage: notify
  image: lddsb/drone-dingtalk-message:1.2.7
  script:
    - drone-dingtalk --build.status success
  when: on_success
```
