### ISSUE TITLE
钉钉消息重复发送

### ISSUE THREAD

**Issue by tangwan** [lddsb/drone-dingtalk-message#41]
使用1.2镜像版本
.gitlab-ci.yaml内容如下
钉钉群收到2条一模一样的消息
大佬有空帮忙瞅瞅啥原因，非常感谢。

```
stages:
  - ding-talk

ding-talk:
  stage: ding-talk
  image: lddsb/drone-dingtalk-message:1.2
  script:
    - drone-dingtalk
  only:
    - dev
    - test
    - pre
  ```

控制台两条发送成功的日志
2022/04/15 04:15:13 send message success!
2022/04/15 04:15:15 send message success!

<img width="761" alt="image" src="https://user-images.githubusercontent.com/15011585/163519184-235d3f95-7f91-46cb-b930-2d1580aa9f54.png">

**Comment by tangwan** [comment]
问题已解决，清除 了ENTRYPOINT 重新制作镜像就可以了，gitlab ci 引入镜像默认就执行了一次，`script: `又执行一次

```
FROM lddsb/drone-dingtalk-message:1.2
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk add --no-cache bash \
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/* $HOME/.cache
ENTRYPOINT [""]
CMD ["/bin/bash"]
```

借用上一个issue方案，获取上一个步骤状态来决定pipeline状态

```
ding-talk-failure:
  stage: ding-talk
  image: xxxx.xxx.xxx/library/dingtalk-gitlab:v1.2
  script:
    - drone-dingtalk --build.status failure
  when: on_failure
  only:
    - master

ding-talk-success:
  stage: ding-talk
  image: xxxx.xxx.xxx/library/dingtalk-gitlab:v1.2
  script:
    -  drone-dingtalk --build.status success
  when: on_success
  only:
    - master
```
