### ISSUE TITLE
自定义 `tips_title` 的时候无法获取真正DRONE_BUILD_STATUS的小问题

### ISSUE THREAD

**Issue by YahuiWong** [lddsb/drone-dingtalk-message#44]
我想要在 `tips_title` 里面 显示 构建状态的时候尝试使用  ` ${DRONE_JOB_STATUS}` `${DRONE_PREV_BUILD_STATUS}` `${DRONE_BUILD_STATUS}` ,发布只有 `DRONE_BUILD_STATUS` 是有值的，而且展示出来的效果永远是 success（实际是failure）

下面是我的代码
```yaml
-   name: DingTalk
    image: lddsb/drone-dingtalk-message
    settings:
        token: 
          from_secret: dingtalk_token
        secret:
          from_secret: dingtalk_secret
        type: markdown
        tips_title: "${DRONE_REPO} build ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}  No.${DRONE_BUILD_NUMBER} ${DRONE_JOB_STATUS}-${DRONE_PREV_BUILD_STATUS}-${DRONE_BUILD_STATUS}"
    when:
        status: [ success, failure ]
```

**Comment by lddsb** [comment]
请问是在GitLab-CI上遇到的问题吗？

**Comment by YahuiWong** [comment]
> 请问是在GitLab-CI上遇到的问题吗？

是在gitea上遇到的问题。

**Comment by lddsb** [comment]
> > 请问是在GitLab-CI上遇到的问题吗？
> 
> 是在gitea上遇到的问题。

我这几天抽空看下

**Comment by lddsb** [comment]
爬了一下论坛，Drone作者表示 `DRONE_JOB_*` 的变量都已经废弃，至于 `DRONE_PREV_BUILD_STATUS` 我没有在[官方文档](https://docs.drone.io/pipeline/environment/reference/)中找到相关的说明
![image](https://user-images.githubusercontent.com/20765867/167333293-304fe487-8aa7-4022-b870-c5c849ce1dd4.png)

**Comment by lddsb** [comment]
至于 `DRONE_BUILD_STATUS` 状态始终为 `success` 的问题，方便提供一下脱敏后完整的 `.drone.yaml` 文件吗？

**Comment by YahuiWong** [comment]
> 至于 `DRONE_BUILD_STATUS` 状态始终为 `success` 的问题，方便提供一下脱敏后完整的 `.drone.yaml` 文件吗？

```
kind: pipeline
type: docker
name: default

steps:
-   name: publish2registry-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    image: plugins/docker
    volumes:
    - name: dockercache
      path: /drone/docker
    - name: dockersock
      path: /var/run/docker.sock
    settings:
        registry: ***
        repo: *****
        tags: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
        username: 
          from_secret: registry_username
        password:
          from_secret: registry_password
        dockerfile: Dockerfile
        pull_image: false
        storage_path: /drone/docker
        use_cache: true
    when:
        event: [push, tag, deployment]
        branch: [dev, staging, master]
-   name: argocd deploy
    image: yahuiwong/drone-argocd-plugin:v2.3.3
    environment:
      ARGOCD_AUTH_TOKEN:
        from_secret: argocd_auth_token 
      ARGOCD_SERVER:
        from_secret: argocd_server
    commands:
      - argocd --insecure app sync ***  --prune
    volumes:
    - name: dockercache
      path: /drone/docker
    - name: dockersock
      path: /var/run/docker.sock
-   name: DingTalk
    image: lddsb/drone-dingtalk-message
    settings:
        token: 
          from_secret: dingtalk_token
        secret:
          from_secret: dingtalk_secret
        type: markdown
        tips_title: "${DRONE_REPO} build ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}  No.${DRONE_BUILD_NUMBER} ${DRONE_JOB_STATUS}-${DRONE_PREV_BUILD_STATUS}-${DRONE_BUILD_STATUS}"
    when:
        status: [ success, failure ]
    volumes:
    - name: dockercache
      path: /drone/docker
    - name: dockersock
      path: /var/run/docker.sock
volumes:
- name: dockercache
  host:
    path: /data/cache/drone.docker
- name: dockersock
  host:
    path: /var/run/docker.sock
```
