### ISSUE TITLE
why not use my tpl?

### ISSUE THREAD

**Issue by Veitor** [lddsb/drone-dingtalk-message#7]
my `.drone.yml`:
```yaml
kind: pipeline
name: test-ci-notification

steps:
  - name: notification
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingTalkToken
      type: markdown
      tpl: ./ci-notification.tpl
```

and I put my `tpl` file named `ci-notification.tpl` in git repository root directory. but message I received don't use my tpl content.
Is my `tpl` setting is wrong?
